### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by HoustonDad** [HoustonDad/ea-apache2-bluehost#1]
From @karljohns0n

> Thanks for the fork, I'll take a look at it. Yes it seems that the Bluehost patch cause more performance degradation then the Rack911 one so the second one should be preferred. Suggestion, wouldn't be more simple to add a new package (ie: ea-apache24-sympatch) that has "Provides: ea-apache24" so this way it could be supported by EA and we can use "yum swap ea-apache24 ea-apache24-sympatch) to swap from regular apache to the patched one? If the patched packages aren't in an official repo, I don't think customers will use it at all.

 I'll work on adding the Rack911 patch here in a bit, and I'll add it to my account and link it here for you. 

With respect to the naming, what improvements would be made from doing so? The new way would call 'yum swap', but the old way was just 'yum update'. With respects to uninstalling / downgrading, you would still need to remove the rest of the packages that are provided / built from the new sources, so I don't see an improvement there either. 

Thanks for your time!

**Comment by karljohns0n** [comment]
IMO the improvement of having a different package of the patched apache would the possibility to integrate it easily in EA4 without adding a new/custom repository. If you choose the package with the patch in EA4 (ie: ea-apache24-patch), it will conflict with ea-apache24 and will install the patched apache (by setting the Conflict and Provides in the spec). You could also use yum swap as I said to swap between the standard and patched apache. This way, cPanel customers could still use this patch with EA4 for those who cannot workaround the issue with the kernel. It would be good to see if you have any stats of your customers who use this patch in EA3 to confirm if it's worth it.

**Comment by HoustonDad** [comment]
Hi Karl,

I see where you're coming from. There are no plans right now to integrate this module upstream with EA4, so this is the best we get right now :)

**Comment by karljohns0n** [comment]
Ok, too bad :) My suggestion was a way to keep this EA3 patch in EA4 to make EA4 migration easier. Packages in a custom repository outside EA wont be used by customers as it wont be officially supported nor integrated in the UI. I'll keep watching the changelog to see if it gets included in the futur. Thanks!
